steps:
  - name: 'ubuntu:bionic'  
    entrypoint: 'bash'
    args:
      - |
        RUN apt-get -y update
        apt-get install chromium-browser wget unzip python3 python3-pip python3-venv -y

        version=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$(chromium-browser --version | grep -oP 'Chromium \K\d+'))
        wget https://chromedriver.storage.googleapis.com/${version}/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip -d /usr/bin
        rm chromedriver_linux64.zip

        cd tipsy_tuesday

        python3 -m venv venv
        source venv/bin/activate
        pip3 install -r requirements.txt

        python3 -m pytest --cov=application --cov-report xml -v
timeout: 180s
