steps:
  - name: 'python'  
    entrypoint: 'bash'
    args:
      - -c
      - |
       
        cd tipsy_tuesday

        python3 -m venv venv
        source venv/bin/activate
        pip3 install -r requirements.txt

        python3 -m pytest --cov=application --cov-report xml -v
timeout: 180s
